### ISSUE TITLE
request example documentation on using extendScraperFunction to filter urls

### ISSUE THREAD

**Issue by LynnWalton** [pocesar/actor-shopify-scraper#2]
Would you consider adding a quick example to the readme showing how to use the extendScraperFunction to achieve sitemap filtering before scraping/crawling? 

Thanks!

**Comment by LynnWalton** [comment]
If you could just show a little sample of code where you've done this or a screenshot, it would help me figure it out.

**Comment by pocesar** [comment]
hi @LynnWalton, in the Extend Scraper Function you can use something like this: 

```js
async ({ label, filteredSitemapUrls }) => {
  if (label === 'SETUP') {
     // filteredSitemapUrls is a Set instance
     for (const url of filteredSitemapUrls) {
        // delete things you don't want
        filteredSitemapUrls.delete(url);  
     }
  }
}
```

but this is only in regards of the actual `sitemap.xml`, not the filtering. It would require adding a new `label` there for filtering, so you can do like this:

```js
async ({ label, filter, url }) => {
   if (label === 'FILTER_SITEMAP_URL') {
       // set a boolean here, since the return value is ignored for the
       // extend scraper function
       filter(url.includes('/something/you/need'));
   }
}
```

**Comment by pocesar** [comment]
done, made the code changes and added to README

**Comment by LynnWalton** [comment]
Thanks so much!
